<?php

namespace App\Filament\Resources\TransactionResource\Pages;

use App\Filament\Resources\TransactionResource;
use App\Models\Balance;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateTransaction extends CreateRecord
{
    protected static string $resource = TransactionResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $type = $data['type'];
        $amount = $data['amount'];
        if($type == "out")
            $amount = -$amount;
        $balance = Balance::findOrFail($data['balance_id']);
        $balance->amount += $amount;
        $balance->save();
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
