<?php

namespace App\Filament\Resources\IncomeResource\Pages;

use App\Filament\Resources\IncomeResource;
use App\Models\Wallet;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateIncome extends CreateRecord
{
    protected static string $resource = IncomeResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $amount = $data['amount'];
        $balance = "balance_" . $data['currency'];
        $wallet = Wallet::findOrFail($data['wallet_id']);
        $wallet->$balance += $amount;
        $wallet->save();
//        dd($wallet);
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
