<?php

namespace App\Filament\Resources\WalletsTransactionResource\Pages;

use App\Filament\Resources\WalletsTransactionResource;
use App\Models\Balance;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateWalletsTransaction extends CreateRecord
{
    protected static string $resource = WalletsTransactionResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        // To
        $amount = $data['amount_to'];
        $balance = Balance::findOrFail($data['balance_to']);
        $balance->amount += $amount;
        $balance->save();
        // From
        $amount = -$data['amount_from'];
        $balance = Balance::findOrFail($data['balance_from']);
        $balance->amount += $amount;
        $balance->save();
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }

    protected function getRedirectUrl(): string
    {
        return WalletsTransactionResource::getUrl('edit', [
            'record' => $this->record
        ]);
    }
}
