<?php

namespace App\Filament\Resources\WalletsTransactionResource\Pages;

use App\Filament\Resources\WalletsTransactionResource;
use App\Models\Wallet;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateWalletsTransaction extends CreateRecord
{
    protected static string $resource = WalletsTransactionResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        // To
        $amount = $data['amount_to'];
        $wallet = Wallet::findOrFail($data['wallet_to']);
        $balance = "balance_" . $data['currency_to'];
        $wallet->$balance += $amount;
        $wallet->save();
        // From
        $amount = -$data['amount_from'];
        $wallet = Wallet::findOrFail($data['wallet_from']);
        $balance = "balance_" . $data['currency_from'];
        $wallet->$balance += $amount;
        $wallet->save();
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
